A more detailed readme
tesla-android/flutter-app pull request #25
Opened 2023-06-05 08:45 UTC by Lettly

When I tried to build and run the app I encountered multiple errors/difficulties, so I decided to update the readme.
I'm not a flutter developer so I tried to make the readme as inclusive as possible (for theta reason I also included how to setup flutter etc..).

2023-06-05 10:16 UTC, mikegapinski requested changes
I'll revisit and merge after pushing gps/virtual display changes. Some things will need to be updated.

Please rebase this branch and squash everything into one commit. Amend & force push later on. Makes the git history cleaner

2023-06-05 10:16 UTC, mikegapinski commented on README.md
> +dart run build_runner build --delete-conflicting-outputs
flutter packages pub is correct btw

2023-06-05 10:16 UTC, mikegapinski commented on README.md
> +You also need to set the ```hostname``` inside ```web/player.html``` to the IP of your Tesla Android device (probably ```100.64.255.1```)
I'll remove the player.html in the next release, just fyi. I'll update your branch with the readme

2023-06-05 10:16 UTC, mikegapinski commented on README.md
> +You need to enable the setting ```_enableIpOverride``` inside ```lib/common/di/app_module.dart```
It would be nice to enable entrypoint based flavors instead of _enableIpOverride, I'm just lazy

2023-06-05 10:16 UTC, mikegapinski commented on README.md
> +## Build
There is no need for the build section. Running a dev version from Android studio is enough, the build process is automated and handled via Jenkins for all branches(pull requests included)

2023-06-05 13:30 UTC, Lettly commented on README.md
> +dart run build_runner build --delete-conflicting-outputs
Yes, but it's deprecated, on the latest version of flutter.
![image](https://github.com/tesla-android/flutter-app/assets/24634460/524abb5f-17c3-4bbc-b44c-e0f9f65119cd)

2023-06-17 19:42 UTC, mikegapinski commented
@Lettly fiy

player.html has been nuked and the process for developing/testing the app has changed slightly.

1. In order to run the app locally only _domainOverride needs to be set to true
2. You need to connect to the network provided by the device in order to access it (SSL)

2024-02-06 08:41 UTC, closed without merging